services:
  web:
    container_name: 'PHP-SERVER-UBC'
    build: ./docker-build/php
    volumes:
    - .:/var/www/ubccreation
    ports:
      - 80:80
    depends_on:
      - mysql-srv
      
  mysql-srv:
  build: ./docker-build/mysql
    # image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: I*LiveForMySelf1602!
      MYSQL_DATABASE: ubc_db
      MYSQL_USER: aurele
      MYSQL_PASSWORD: IAmFreeNow!411
    ports:
      - '3306:3306'
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
  # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8076:80"
    depends_on:
    - mysql-srv

    # links:
    #   - mysql-srv:db